"""imports table

Revision ID: 3580c7994661
Revises: 
Create Date: 2019-08-18 15:06:52.236263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3580c7994661'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.Column('relatives', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id')
    )
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imports')
    op.drop_table('citizens')
    # ### end Alembic commands ###
