"""citizens table

Revision ID: 52f55f2e67de
Revises: 52cb6fc73223
Create Date: 2019-08-18 16:44:03.507728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f55f2e67de'
down_revision = '52cb6fc73223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citizens', 'gender',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('citizens', 'relatives',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citizens', 'relatives',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('citizens', 'gender',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
