"""citizens table

Revision ID: 6618224cdf15
Revises: 54487aad78cd
Create Date: 2019-08-18 17:02:43.534438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6618224cdf15'
down_revision = '54487aad78cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizens',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=128), nullable=False),
    sa.Column('relatives', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citizens')
    op.drop_table('imports')
    # ### end Alembic commands ###
